name: Unity Testing

on:
  push:           # run on push
  pull_request:   # run on PRs

jobs:
  editmode:
    name: EditMode testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Caching
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('ProjectSettings/ProjectVersion.txt', 'Packages/manifest.json', 'Packages/packages-lock.json') }}
          restore-keys: |
            Library-${{ runner.os }}-
            Library-

        
      - name: Testing
        uses: game-ci/unity-test-runner@v4
        with:
          projectPath: .
          unityVersion: auto
          testMode: EditMode
          artifactsPath: artifacts
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

          
      - name: Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: editmode-results
          path: artifacts
